[package]
name = "sovereigntycore"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
organiccpucore = { path = "../organiccpucore" }
organiccpualn = { path = "../organiccpualn" }
